# Generated by Django 4.2 on 2023-05-06 14:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_ticket_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="started",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, verbose_name="start date"
            ),
        ),
    ]
