# Generated by Django 4.2 on 2023-05-06 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_project_started"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_manager",
            field=models.ForeignKey(
                limit_choices_to=models.Q(("role__contains", "PM")),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
