# Generated by Django 4.2 on 2023-05-06 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_project_description_alter_project_project_manager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="project_manager",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
